=== Cheng17415/XML/TrabajoVS-20250516T131652Z-1-001/TrabajoVS/3tri_LM/zejercicioCompleto/ejercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipo_prestado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="si"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:group name="info_libro">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="autor">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="pais" type="xs:string" use="optional"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="anno" type="xs:string" minOccurs="0"/>
            <xs:element name="genero" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="estado" minOccurs="0">
                <xs:complexType>
                    <xs:attributeGroup ref="atr_estado"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="idioma" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="edicion" type="xs:string" minOccurs="0"/>
            <xs:element name="sinopsis" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="atr_estado">
        <xs:attribute name="prestado" type="tipo_prestado"/>
        <xs:attribute name="fecha_devolucion" type="xs:date"/>
    </xs:attributeGroup>

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="info_libro"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Cheng17415/XML/TrabajoVS-20250516T131652Z-1-001/TrabajoVS/3tri_LM/zejercicioCompleto/ejercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro)+>
    <!ELEMENT libro (titulo, autor, anno?, genero*, estado?, idioma*, edicion?, sinopsis)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
        <!ATTLIST autor pais CDATA #IMPLIED>   
    <!ELEMENT anno (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
    <!ELEMENT estado EMPTY>
    <!ATTLIST estado 
        prestado (si|no) #REQUIRED 
        fecha_devolucion CDATA #IMPLIED>
    <!ELEMENT idioma (#PCDATA)>
    <!ELEMENT edicion (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
]> -->
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio.xsd">
    <libro>
        <titulo>El quijote</titulo>
        <autor pais="España">Miguel de Cervantes</autor>
        <anno>1605</anno>
        <genero>Novela</genero>
        <estado prestado="si" fecha_devolucion ="2023-05-16"/>
        <idioma>Inglés</idioma>
        <idioma>Francés</idioma>
        <edicion>Primera</edicion>
        <sinopsis>Un libro sobre las aventuras de un caballero loco.</sinopsis>
    </libro>
</biblioteca>
