=== Cheng17415/XML/TrabajoVS-20250516T131652Z-1-001/TrabajoVS/3tri_LM/XSD/4_libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="fecha-publicacion" type="xs:date"/>
                <xs:element name="precio" type="xs:decimal"/>
                <xs:element name="disponible" type="xs:boolean"/>
                <xs:element name="fecha-ingreso" type="xs:date"/>  
                <xs:element name="tipo" type="xs:string" fixed="Libro"/>
                <xs:element name="ejemplares" type="xs:integer" default="5"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Cheng17415/XML/TrabajoVS-20250516T131652Z-1-001/TrabajoVS/3tri_LM/XSD/4_libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="4_libros.xsd">
  <titulo>1984</titulo>
  <fecha-publicacion>1949-06-08</fecha-publicacion>
  <precio>14.99</precio>
  <disponible>false</disponible>
  <fecha-ingreso>2023-01-10</fecha-ingreso>
  <tipo>Libro</tipo>
  <ejemplares>3</ejemplares>
</libro>
